name: actions_rbr
on: [push]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Check out respository under $GITHUB_WORKSPACE, so job can access
      # it
      - uses: actions/checkout@v2
      # Run pre-commit
      - run: pip install pre-commit
      - run: pre-commit run -a

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
              os: ['windows-latest', 'ubuntu-latest', 'macos-latest']

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: 3.7

    - run: pip install -r requirements.txt pyinstaller
    - run: pyinstaller --onefile main_rbr.py
    # Optionally verify that it works (provided that it does not need user interaction)
    # - ./dist/main_rbr/main_rbr
    - uses: actions/upload-artifact@v2
      with:
        path: dist/*
  
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Install deps
      - run: sudo apt install -y -qq cmdtest
      # Run tests
      - run: . check
